In [70]:
import numpy as np

# Завдання 1 - 1D массив

In [71]:
arr = np.random.randint(1, 101, 10)

print("Масив:", arr)
print("Перший елемент:", arr[0])
print("Центральний елемент:", arr[5])
print("Останній елемент:", arr[-1])

Масив: [63 94 33 69  9 45 77  4  8 43]
Перший елемент: 63
Центральний елемент: 45
Останній елемент: 43


# Завдання 2 - масив від 10 до 50 та зріз

In [72]:
arr = np.arange(10, 51)
print(arr[::-3])

[50 47 44 41 38 35 32 29 26 23 20 17 14 11]


# Завдання 3 - матриця 4х4 та підматриця

In [73]:
matrix = np.arange(1, 17).reshape(4, 4)

print("Матриця:")
print(matrix)

print("\nПідматриця 2x2 у правому верхньому куті:")
print(matrix[:2, 2:])

Матриця:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Підматриця 2x2 у правому верхньому куті:
[[3 4]
 [7 8]]


# Завдання 4 - матриця 5х5

In [74]:
matrix = np.random.randint(1, 101, (5, 5))

print("Матриця:")
print(matrix)

print("\nЦентральний елемент:", matrix[2, 2])
print("Третій стовпчик:", matrix[:, 2])

Матриця:
[[77 63 28 83 60]
 [49 35 33 81 68]
 [34 74 33 60  8]
 [98 78 29 42 86]
 [73 97 92 18 16]]

Центральний елемент: 33
Третій стовпчик: [28 33 33 29 92]


# Завдання 5 - позитивні числа через булеву маску

In [75]:
arr = np.random.randint(-10, 11, 10)

print("Масив:", arr)
print("Додатні значення:", arr[arr > 0])

Масив: [  2  -9 -10  -9   2   2  -2   6   1   0]
Додатні значення: [2 2 2 6 1]


# Завдання 6 - кількість чисел, кратних 3

In [76]:
arr = np.arange(1, 21)

print("Масив:", arr)

count = np.sum(arr % 3 == 0)

print("Кількість чисел, що діляться на 3:", count)

Масив: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Кількість чисел, що діляться на 3: 6


# Завдання 7 - фільтрація за двома умовами

In [77]:
arr = np.random.randint(0, 101, 12)

print("Масив:", arr)
print("Елементи від 20 до 80:", arr[(arr > 20) & (arr < 80)])

Масив: [99 99 38 53 53 88 64 65 33 50 43 49]
Елементи від 20 до 80: [38 53 53 64 65 33 50 43 49]


# Завдання 8 - заміна парних чисел на 0

In [78]:
arr = np.arange(1, 13).reshape(3, 4)

print("Початковий масив:")
print(arr)

arr[arr % 2 == 0] = 0

print("\nМасив після заміни парних чисел:")
print(arr)

Початковий масив:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Масив після заміни парних чисел:
[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]]
